version: '3'
services:
  user-service:
    container_name: user-service
    build: ./users
    ports:
      - '3000:3000'
    volumes:
      - ./users:/usr/src/app
    env_file:
      - ./users/.env
    command: ['/bin/sh', '-c', 'yarn install --production=false && yarn dev']
    networks:
      - microservices
    depends_on:
      - mongo

  showtime-service:
    container_name: showtime-service
    build: ./showtimes
    ports:
      - '3001:3001'
    volumes:
      - ./showtimes:/usr/src/app
    env_file:
      - ./showtimes/.env
    command: ['/bin/sh', '-c', 'yarn install --production=false && yarn dev']
    networks:
      - microservices
    depends_on:
      - mongo

  reservation-service:
    container_name: reservation-service
    build: ./reservations
    ports:
      - '3002:3002'
    volumes:
      - ./reservations:/usr/src/app
    env_file:
      - ./reservations/.env
    command: ['/bin/sh', '-c', 'yarn install --production=false && yarn dev']
    networks:
      - microservices
    depends_on:
      - mongo
      - user-service
      - showtime-service

  mongo:
    container_name: mongo
    image: mongo:4.4.5
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/db
    networks:
      - microservices
    environment:
      - MONGO_INITDB_ROOT_USERNAME=homestead
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=movieTheater

networks:
  microservices:
